apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: busybox
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: busybox:latest
    name: latest
    referencePolicy:
      type: Source
